"""Initial Restaurant table

Revision ID: 46510be9c765
Revises: 
Create Date: 2025-06-15 15:22:08.090759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46510be9c765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('Restaurant', sa.String(length=100), nullable=False),
    sa.Column('compound', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=100), nullable=False),
    sa.Column('year_create', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    op.drop_table('orders')
    op.drop_table('menu')
    # ### end Alembic commands ###
